alias and='cd /home/robespierre/Dropbox/programming/android'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lat='ls -lArt'
alias wugsc='ssh rlong@wugsc.wustl.edu'
alias bm='ssh robes@172.16.1.50'
alias linus='ssh rlong@10.0.3.47'
alias linusx='ssh -X rlong@10.0.3.47'
alias vpnstart='sudo /etc/init.d/openvpn start'
alias vpnstop='sudo /etc/init.d/openvpn stop'
alias saasbookx='ssh -X -C -c blowfish -i /home/robespierre/Downloads/saasbook.pem ubuntu@ec2-174-129-106-100.compute-1.amazonaws.com'
alias saasbook='ssh -i /home/robespierre/Downloads/saasbook.pem ubuntu@ec2-174-129-106-100.compute-1.amazonaws.com'
alias adk='cd $ADK/tools'

